<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RCO6D0F" name="com.qa.hubspot.tests.HomePageTest" tests="3" failures="1" timestamp="29 Jun 2020 15:01:48 GMT" time="5.303" errors="0">
  <testcase name="verifygetHomePageHeaderTest" time="5.251" classname="com.qa.hubspot.tests.HomePageTest"/>
  <testcase name="verifyhomePageTitleTest" time="0.011" classname="com.qa.hubspot.tests.HomePageTest"/>
  <testcase name="verifyLoggedinUserTest" time="0.041" classname="com.qa.hubspot.tests.HomePageTest">
    <failure type="java.lang.AssertionError" message="Logged in user is matched expected [ArjunTest Company] but found [null]">
      <![CDATA[java.lang.AssertionError: Logged in user is matched expected [ArjunTest Company] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.qa.hubspot.tests.HomePageTest.verifyLoggedinUserTest(HomePageTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyLoggedinUserTest -->
</testsuite> <!-- com.qa.hubspot.tests.HomePageTest -->
